name: Build and Sync to /www

on:
  push:
    branches:
      - master # Replace with the default branch of your repo if it's not "main"

jobs:
  build-and-sync:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14 # You can use any version of Node.js that you need

    - name: Install dependencies and run build.sh
      run: |
        chmod +x build.sh
        sh build.sh

    - name: Deploy /www directory to master gh-pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./www
        publish_branch: master # Replace with your desired branch name for deployment
